name: Reach App Deployed with Surge

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12
      uses: actions/setup-node@v2-beta
      with:
        node-version: 12
    - name: Installing Yarn
    - uses: borales/actions-yarn@v2.0.0
      with:
        cmd: install # will run `yarn install` command
    - name: install surge on git
      run: npm install --global surge

    - name: upload files through surge
      run: surge ./build sasadaliz.surge.sh --token ${{ secrets.SURGE_TOKEN }}
