name: Boot Camp 2020

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Installing Node JS 
      uses: actions/setup-node@v2-beta
      with:
        node-version: 12 
    - name: Installing surge
      run: npm install --global surge
    - uses: actions/checkout@v1
    - name: Install Yarn
      uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install # will run `yarn install` command
    - name: Build File
      run: yarn build 
    - name: deploying Surge
      run: surge ./build sasadaliz.surge.sh --token  ${{ secrets.SURGE_TOKEN }}